package com.ocoelhogabriel.manager_user_security.application.service;

import com.ocoelhogabriel.manager_user_security.domain.model.User;
import com.ocoelhogabriel.manager_user_security.domain.model.value_objects.*;
import com.ocoelhogabriel.manager_user_security.domain.ports.in.UserUseCase;
import com.ocoelhogabriel.manager_user_security.domain.ports.out.PasswordHashingService;
import com.ocoelhogabriel.manager_user_security.domain.ports.out.UserRepository;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Application Service implementing the UserUseCase input port.
 * This class orchestrates the business logic for user management.
 */
public class UserService implements UserUseCase {

    private final UserRepository userRepository;
    private final PasswordHashingService passwordHashingService;

    public UserService(final UserRepository userRepository, final PasswordHashingService passwordHashingService) {
        this.userRepository = Objects.requireNonNull(userRepository);
        this.passwordHashingService = Objects.requireNonNull(passwordHashingService);
    }

    @Override
    public User createUser(final CreateUserCommand command) {
        final Name name = new Name(command.name());
        final CPF cpf = new CPF(command.cpf());
        final Username username = new Username(command.username());
        final Email email = new Email(command.email());
        final EmpresaId empresaId = new EmpresaId(command.empresaId());
        final PerfilId perfilId = new PerfilId(command.perfilId());
        final AbrangenciaId abrangenciaId = new AbrangenciaId(command.abrangenciaId());

        if (userRepository.existsByUsername(username) || userRepository.existsByEmail(email) || userRepository.existsByCpf(cpf)) {
            throw new UserAlreadyExistsException("A user with the same username, email, or CPF already exists.");
        }

        final HashedPassword hashedPassword = new HashedPassword(passwordHashingService.hash(command.rawPassword()));
        final LocalDateTime now = LocalDateTime.now();

        final User newUser = User.builder()
            // ID is not set here; it will be generated by the database upon persistence.
            .name(name)
            .cpf(cpf)
            .username(username)
            .email(email)
            .password(hashedPassword)
            .empresaId(empresaId)
            .perfilId(perfilId)
            .abrangenciaId(abrangenciaId)
            .active(true)
            .createdAt(now)
            .updatedAt(now)
            .build();

        return userRepository.save(newUser);
    }

    @Override
    public User findById(final UserId id) {
        return userRepository.findById(id)
            .orElseThrow(() -> new UserNotFoundException("User not found with ID: " + id.value()));
    }

    @Override
    public PagedResult<User> findAllActive(final PageQuery query) {
        return userRepository.findAllActive(query);
    }

    @Override
    public User updateEmail(final UpdateEmailCommand command) {
        final User existingUser = findById(command.id());
        final User updatedUser = existingUser.updateEmail(command.newEmail());
        return userRepository.save(updatedUser);
    }

    @Override
    public User deactivateUser(final UserId id) {
        final User existingUser = findById(id);
        final User deactivatedUser = existingUser.deactivate();
        return userRepository.save(deactivatedUser);
    }
}
